### ISSUE TITLE
Shaders compatability

### ISSUE THREAD

**Issue by leafable** [W-OVERFLOW/WeatherChanger#3]
### Bug description

Rain puddles don't work while using shaders.

### Steps to reproduce

1. Put on shaders (optifine, I used complementary shaders but it also breaks with other shaders).
2. Turn on rain puddles in Materials>Rain Puddles.

### Expected behavior

The top of the block should be specular and have rain puddles.

### Anything else?

Badlion's weather changer doesn't have this bug, just for visual reference.

**Comment by Wyvest** [comment]
I think we need to change the mod entirely to use mixin instead of separate "handlers"

**Comment by leafable** [comment]
Its very minor, but it looks very nice for replay renders.

**Comment by Scherso** [comment]
damn
i need to do work

**Comment by Scherso** [comment]
> I think we need to change the mod entirely to use mixin instead of separate "handlers" to fix it

I could probably get it working, i didn’t check for optifine settings in the renderer handlers

**Comment by Scherso** [comment]
Rain puddles and other rain functions are now working with the rewrite that’s in progress @leafable 👍 It took a while lol

**Comment by EthanDevelops** [comment]
The mod has been rewritten, this issue is no longer relevant to the mod.
